### ISSUE TITLE
API URL doesn't seem to be working

### ISSUE THREAD

**Issue by tonyflo** [amarder/diamonds#1]
I'm running your script out-of-the-box (for the most part, with a few tweaks for python 3.5 compatibility), but I'm consistently getting back a "File Not Found" response from http://www.bluenile.com/api/public/diamond-search-grid/solr. Can you confirm this? Perhaps the API was taken offline.  On that note, how did you come across the BlueNile API? Is there documentation for it?

**Comment by amarder** [comment]
Hi @flooreeda,

It looks like Blue Nile has changed their API. Here's a search for round diamonds:

http://www.bluenile.com/api/public/diamond-search-grid/v2?country=USA&language=en-us&currency=USD&startIndex=0&pageSize=243&shape=RD&sortColumn=price&sortDirection=asc&_=1468875090671

It may take me a little while to get things up and running with the new (unofficial) API.

Andrew
